environment: 'local'

app:
  bokeh:
    path: "/bokeh/bkapp"
  flask:
    path: "/"

proxy:
  bokeh:
    local:
      address: "127.0.0.1"
      port: "$PORT"
      path: "/bokeh/bkapp/ws"
  flask:
    local:
      address: "127.0.0.1"
      port: 8000
      path: "/"
    heroku:
      domain: "cx4242fall2021.herokuapp.com"
      address: "0.0.0.0"
      port: "$PORT"
      path: "/"

cdn:
  bokeh:
    url: "https://cdn.bokeh.org/bokeh/release"
